### ISSUE TITLE
Incorrect port mapping on VirtualBox

### ISSUE THREAD

**Issue by SJGeorge3108** [tdaly61/mini-loop#12]
I had an issue today getting mini-loop set up on Mac OS 11.6.2, was unable to get mini-loop running and it ended up being due to the host port and the guest port being assigned the wrong numbers.

Followed your README and installed Vagrant using brew and added the entries to the /etc/hosts files.

was having issues accessing the testing toolkit and turned out the Host Port and the Guest Port were assigned each others numbers in the Network settings in VirtualBox.

**Comment by tdaly61** [comment]
closing as mini-loop has moved away from providing VM automation for the moment
