### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by vorburger** [tdaly61/mini-loop#2]
In the context of https://github.com/mojaloop/helm/issues/342, I was considering "stealing" (= honest word for "taking friendly inspiration from") some of your scripts in this repo. My next goal after https://github.com/mojaloop/helm/pull/348 is to have a `install-remote-minikube.sh` kind of script which "does it all", and it occurred to me that I could re-use things like https://github.com/tdaly61/mini-loop/blob/master/scripts/01_install_miniloop.sh#L87.

However, I currently cannot do that because this repository is missing a LICENSE file which states under what condition you make the code (scripts) in this repository available to the public. Until clarified, I have to avoid copy/pasting anything from here.

Would you be willing to use e.g. https://choosealicense.com to add a LICENSE to this repository? If you would like to permit (me and others) to copy/paste lines from here to https://github.com/mojaloop, then using https://choosealicense.com/licenses/apache-2.0/ would be simplest (because https://github.com/mojaloop/helm/blob/master/LICENSE.md).

**Comment by lewisdaly** [comment]
Thanks @vorburger for pointing this out. This is a Mojaloop Community contribution, so I'll put in the Apache 2.0 license we use across most of the Mojaloop codebase.
