### ISSUE TITLE
Windows Line ending Issues

### ISSUE THREAD

**Issue by lewisdaly** [tdaly61/mini-loop#5]
For windows hosts, when mounting in the `./scripts` directory, the scripts contain windows line endings (`\r\n`), which causes the scripts (which run inside the ubuntu guest) to fail.

We have some hacky workarounds for now, but there should be a way to make sure that windows doesn't mess around with the file endings during the `git clone`.

**Comment by tdaly61** [comment]
for the moment mini-loop is assuming is it being used inside an ubuntu OS, it is expected this is the best way to run on windows is to use a hypervisor and create an ubuntu VM
